app/models.py
from app import db


class Student(db.Model):
    # 表名：students
    # 列含义：id，学号， 学生姓名，学生性别，年级，专业id，班级id，层次（本科），学制（4年）
    __tablename__ = 'students'
    id = db.Column(db.Integer(), primary_key=True)
    number = db.Column(db.String(64), index=True, nullable=False, unique=True)
    name = db.Column(db.String(64), index=True, nullable=False)
    sex = db.Column(db.String(64), nullable=False)
    grade = db.Column(db.Integer, nullable=False)
    marjor_id = db.Column(db.Integer, db.ForeignKey('marjors.id'))
    class_id = db.Column(db.Integer, db.ForeignKey('classes.id'))
    level = db.Column(db.String(64), nullable=False, default='本科')
    length_of_schooling = db.Column(db.Integer, nullable=False, default=4)
    scores = db.relationship(
        'Score',
        backref='students',
        lazy='dynamic'
    )

    def __repr__(self):
        return '<Student %r>' % self.name


class Score(db.Model):
    # 表名：scores
    # 列含义：id，学年，学期， 学生id，课程id，原考成绩，补考成绩
    __tablename__ = 'scores'
    id = db.Column(db.Integer(), primary_key=True)
    year = db.Column(db.Integer, nullable=False)
    term = db.Column(db.Integer, nullable=False)
    stu_id = db.Column(db.Integer, db.ForeignKey('students.id'))
    course_id = db.Column(db.Integer, db.ForeignKey('courses.id'))
    score1 = db.Column(db.String(64), nullable=False)
    score2 = db.Column(db.String(64), nullable=True)  # 补考成绩可为空

    def __repr__(self):
        return '<Score_id %r>' % self.id


class Major(db.Model):
    # 表名：marjors
    # 列含义：id， 专业名称
    __tablename__ = 'marjors'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(64), nullable=False, index=True)
    students = db.relationship(
        'Student',
        backref='marjors',
        lazy='dynamic'
    )

    def __repr__(self):
        return '<Major %r>' % self.name


class Class(db.Model):
    # 表名：classes
    # 列含义：id，班级名称
    __tablename__ = 'classes'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(64), nullable=False, index=True, unique=True)
    students = db.relationship(
        'Student',
        backref='classes',
        lazy='dynamic'
    )

    def __repr__(self):
        return '<Class %r>' % self.name


class Course(db.Model):
    # 表名：courses
    # 列含义：id，课程名，课程类型
    __tablename__ = 'courses'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(64), nullable=False, index=True)
    category = db.Column(db.String(64), nullable=False)
    power = db.Column(db.Float, nullable=False)
    scores = db.relationship(
        'Score',
        backref='courses',
        lazy='dynamic'
    )

    def __repr__(self):
        return '<Course %r>' % self.name

app/__init__.py
from config import config
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    # config[config_name].init_app(app=app)

    db.init_app(app)

    from .main import main as blueprint_main
    app.register_blueprint(blueprint_main)

    from .auth import auth as blueprint_auth
    app.register_blueprint(blueprint_auth)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import render_template, request, jsonify
from . import main
from app.models import Student, Major, Class


@main.route('/index')
@main.route('/')
def index():
    stu = Student.query.all()
    marjor = Major.query.all()
    _class = Class.query.all()
    return render_template(
        'index.html',
        count_stu=len(stu),
        count_marjor=len(marjor),
        count_class=len(_class))


@main.route('/login')
def login():
    return render_template("login.html")


@main.route('/register')
def register():
    return render_template("register.html")


@main.route('/student')
def student():
    return render_template("student.html")


@main.route('/student_info')
def stu_info():
    stu_num = request.args['student_number']
    print(stu_num)
    this_student = Student.query.filter_by(number=stu_num).first()
    if this_student:
        return jsonify({
            'number': this_student.number,
            'name': this_student.name,
            'sex': this_student.sex,
            'grade': this_student.grade,
            'marjor': this_student.marjors.name,
            'class': this_student.classes.name,
            'level': this_student.level,
            'length_of_schooling': this_student.length_of_schooling
        })
    else:
        return jsonify({
            'number': 'none',
            'name': 'none',
            'sex': 'none',
            'grade': 'none',
            'marjor': 'none',
            'class': 'none',
            'level': 'none',
            'length_of_schooling': 'none'
        })


@main.route('/theme')
def theme():
    return render_template("theme.html")

spider/__init__.py
from . import xhcx #学号查询
from . import zcjcx # 总成绩查询

app/templates/base.html
<!DOCTYPE html>
<html lang="zn">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{{ url_for('static',filename='css/base.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/buttons.css') }}" type="text/css">
    {% block header %}
    {% endblock %}
</head>
<body id="body" background="{{ url_for('static',filename="img/default_background.jpeg") }}">

<div id="nav">
    <div id="header">
        <div class="header1">
            <img src="{{ url_for('static',filename="img/sdut.gif") }}"/>
        </div>
        <div class="header2">
            <p>学生信息统计总览</p>
        </div>
        <div class="header3">
            <a href="#">登录</a>
            <a href="{{ url_for('main.register') }}">注册</a>
        </div>
    </div>
    <div id="menu">

        <a href="{{ url_for('main.index') }}">
            <button class="button button-primary button-rounded button-large">首页</button>
        </a>
        <a href="{{ url_for('main.student') }}">
            <button class="button button-primary button-rounded button-large">学生信息查询</button>
        </a>
        <a href="{{ url_for('main.theme') }}">
            <button class="button button-primary button-rounded button-large">主题更换</button>
        </a>
        <a href="#">
            <button class="button button-primary button-rounded button-large" disabled="disabled">图书借阅查询</button>
        </a>
        <a href="#">
            <button class="button button-primary button-rounded button-large" disabled="disabled">未开放</button>
        </a>
        <a href="#">
            <button class="button button-primary button-rounded button-large" disabled="disabled">未开放</button>
        </a>
    </div>
</div>

<div id="main">
    {% block main %}
    {% endblock %}
</div>

<div id="footer">
    <hr/>
    <div id="copyright">
        <p>SIIS:&nbsp;Students' information in SDUT</p>
        <p>本项目遵循apache&nbsp;LICENSE-2.0协议进行开源，
            <a href="https://github.com/lvhuiyang/SIIS " target="_blank">github地址</a>
        </p>
    </div>
    <div id="author">
        <p>Copyright (c) 2016 All right reserved.&nbsp;Author:
            <a href="http://blog.csdn.net/lvhuiyang" target="_blank">lvhuiyang</a>
        </p>
    </div>
</div>


<script src="{{ url_for('static',filename='js/jquery.js') }}"></script>
<script src="{{ url_for('static',filename='js/echarts.common.js') }}"></script>

{% block script %}{% endblock %}

</body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/index.css') }}" type="text/css">
{% endblock %}


{% block main %}
    <div class="chart">
        <div class="c-top">
            <p class="create">我们收集了<span id="count_stu">{{ count_stu }}</span>名学生信息，
                收集了<span id="count_class">{{ count_class }}</span>个班级信息，
                收集了<span id="count_major">{{ count_marjor }}</span>个专业信息。
                <button class="button button-glow button-border button-rounded button-primary" id="create_chart">
                    点击生成图表
                </button>
            </p>

            <p class="info">数据来源：爬虫至教务处。</p>
        </div>
        <div class="c-bottom">
            <div id="chart_area"></div>
        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{{ url_for('static',filename='js/index.js') }}"></script>
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/register.html
{% extends "base.html" %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/register.css') }}" type="text/css">
{% endblock %}


{% block main %}
    <div class="form_area">
        <form action="#" method="get">
            <h4>请输入11位学号和两次相同的密码，密码不能低于6位。</h4>
            <br/>
            <p>学号:&nbsp;<input type="text" class="input" id="stu_number"></p>

            <p>密码:&nbsp;<input type="password" class="input" id="password1"></p>

            <p>密码确认:&nbsp;<input type="password" class="input" id="password2"></p>

            <input type="submit" id="submit" value="提交注册"
                   class="button button-glow button-border button-rounded button-primary">
            <input type="reset" value="重置操作" class="button button-glow button-border button-rounded button-primary">
        </form>
    </div>
{% endblock %}

{% block script %}
    <script src="{{ url_for('static',filename='js/register.js') }}"></script>
{% endblock %}

app/templates/student.html
{% extends "base.html" %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/student.css') }}" type="text/css">
{% endblock %}


{% block main %}
    <div class="form_area">
        <form action="#" method="get">
            <input type="text" class="input" id="stu_number">
            <input type="button" id="submit" value="学号查询"
                   class="button button-glow button-border button-rounded button-primary">
        </form>
    </div>
    <div class="stu_info">
        <table id="stu_info">
            <tr>
                <th>学号</th>
                <th>姓名</th>
                <th>性别</th>
                <th>年级</th>
                <th>专业</th>
                <th>班级</th>
                <th>层次</th>
                <th>学制</th>
            </tr>
            <tr>
                <td>14110543055</td>
                <td>吕绘杨</td>
                <td>男</td>
                <td>2014</td>
                <td>计算机科学与技术（中爱合作办学）</td>
                <td>计科1402(中外)</td>
                <td>本科</td>
                <td>4</td>
            </tr>
        </table>
    </div>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static',filename='js/student.js') }}"></script>
{% endblock %}

app/templates/theme.html
{% extends "base.html" %}

{% block header %}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/theme.css') }}" type="text/css">
{% endblock %}


{% block main %}
    <div style="display: none">
        <p id="img-url1">{{ url_for('static',filename="img/default_background.jpeg") }}</p>
        <p id="img-url2">{{ url_for('static',filename="img/blue_background.jpg") }}</p>
        <p id="img-url3">{{ url_for('static',filename="img/green_background.jpg") }}</p>
    </div>
    <div class="change_theme">
        <div class="theme1">
            <button class="button button-primary button-rounded button-large">主题更换(主题1)</button>
            <img src="{{ url_for('static',filename="img/default_background.jpeg") }}"/>
        </div>
        <div class="theme2">
            <button class="button button-primary button-rounded button-large">主题更换（主题2）</button>
            <img src="{{ url_for('static',filename="img/blue_background.jpg") }}"/>
        </div>
        <div class="theme3">
            <button class="button button-primary button-rounded button-large">主题更换（主题3）</button>
            <img src="{{ url_for('static',filename="img/green_background.jpg") }}"/>
        </div>
        <div class="theme1">
            <button class="button button-primary button-rounded button-large">主题更换(主题1)</button>
            <img src="{{ url_for('static',filename="img/default_background.jpeg") }}"/>
        </div>
        <div class="theme2">
            <button class="button button-primary button-rounded button-large">主题更换（主题2）</button>
            <img src="{{ url_for('static',filename="img/blue_background.jpg") }}"/>
        </div>
        <div class="theme3">
            <button class="button button-primary button-rounded button-large">主题更换（主题3）</button>
            <img src="{{ url_for('static',filename="img/green_background.jpg") }}"/>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script src="{{ url_for('static',filename='js/theme.js') }}"></script>
{% endblock %}